name: Trigger wasm deploy event in rv32emu upon releasing

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  deploy-wasm-dispatch:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Trigger wasm deploy event
        if: contains(github.event.release.tag_name, 'ELF')
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.RV32EMU_WORKFLOW_TOKEN }}" \
            https://api.github.com/repos/sysprog21/rv32emu/dispatches \
            -d '{"event_type": "deploy_wasm"}'
